name: Build Linux Kernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Java Project
        run: |
          sudo apt install tree
          echo $GITHUB_WORKSPACE
          run: cp -rp /README.md /src/.
          tree