name: Build Linux Kernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Java Project
        run: |
          mvn clean package
          sudo dnf install tree
          tree